name: base_ddd
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #data
  dartz: ^0.10.1
  uuid: ^3.0.6

  #ui
  google_fonts: ^3.0.1
  # font_awesome_flutter: ^10.1.0

  #state management
  provider: ^6.0.3
  flutter_bloc: ^8.1.1

  #networking
  http: ^0.13.5
  dio: ^4.0.6
  

dev_dependencies:
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
